[phases.setup]
nixPkgs = ["python312"]

[phases.install]
cmds = [
    "pip install --upgrade pip setuptools wheel",
    "pip install --no-cache-dir -r requirements.txt"
]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "python -m uvicorn backend.main:app --host 0.0.0.0 --port $PORT"
