[phases.setup]
nixPkgs = ["python312"]

[phases.install]
cmds = [
    "pip install --upgrade pip setuptools wheel",
    "pip install --no-cache-dir -r requirements.txt"
]

[phases.build]
cmds = ["echo 'Build complete'"]

[variables]
PYTHONPATH = "/app:$PYTHONPATH"

[start]
cmd = "python -c \"import sys; sys.path.append('.'); import uvicorn; uvicorn.run('main:app', host='0.0.0.0', port=int(__import__('os').environ.get('PORT', 8000)))\""
